print ("marks sheet")
student = str(input("enter the student name :"))
father = str(input("Enter the father name :"))
clas = input("Enter the class :")
section = input("Enter the section :")
english = int(input("Enter the english marks :"))
sanskrit = int(input("Enter the sanskrit marks :"))
costaccounting = int(input("Enter the cost accounting marks :"))
Ecommerce = int(input("Enter the Ecommerce marks :"))
Clang = int(input("Enter the clang marks :"))
Auddting =int(input("Enter the auddting marks :"))
total = english+sanskrit+costaccounting+Ecommerce+Clang+Auddting
average =(english+sanskrit+costaccounting+Ecommerce+Clang+Auddting)/600*100
grade = str(input("Enter grade :"))
print()
print()
print('               MNR degree college   ')
print('              ......................')
print('              final year results    ')
print('           student name:',student,'father name:',father,'class:',clas,'section:',section)
print('                                      ')
print('                   english          :',english)
print('                   sanskrit         :',sanskrit)
print('                   costaccounting   :',costaccounting)
print('                   Ecommerce        :',Ecommerce)
print('                   Clang            :',Clang)
print('                   Auddting         :',Auddting)
print('                                                       ')
print('                    Total    :',total,'out of 600')
print('                    Average  :',average,'%')
print('                                                        ')
print()
if (english<35)or(sanskrit<35)or(costaccounting<35)or(Ecommerce<35)or(Clang<35)or(Auddting<35): 
   print(' result is failed ')

else: 
    print('result is pass')